name: Automated Preprocessing

on:
  push:
    paths:
      - "preprocessing/automate_mifdal.py"
      - "../dataset_raw/**"
      - ".github/workflows/preprocess.yml"
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn

      - name: List dataset_raw contents
        run: ls -l dataset_raw

      - name: Run preprocessing script
        run: python preprocessing/automate_mifdal.py --csv_path dataset_raw/Heart_Disease_Prediction.csv --out_dir preprocessing/dataset/

      - name: Upload preprocessed dataset
        uses: actions/upload-artifact@v4
        with:
          name: heart_disease_preprocessed
          path: preprocessing/heart_disease_preprocessed/
